{% set name = "unicode-display_width" %}
{% set version = "1.7.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: cad681071867a4cf52613412e379e39e85ac72b1d236677a2001187d448b231a

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE.txt
  summary: Determines the monospace display width of a unicode string.

  dev_url: https://github.com/janlelis/unicode-display_width

extra:
  recipe-maintainers:
    - sodre
