travis:
  secure:
    BINSTAR_TOKEN: mRu8K+n85ygZhr4ZY3Ee7PLFE1o1byNu6ycblN0VIFyN9I5HZqO9R9sWaewDLSqRebU9ItKSx9sbOnfFLHmcvDnjSJrcHG9Zyc00WMtz/cd4kF2Rb9ypFHmB4TFQQU7iFuuOq5ZQLzpZJHfBMwhthcW1+Ur8Z15wE0XleK7QijaUJoHZ37ieQYl2qy5f1CmYJ7kP2b0lHCugq+UxRUY+6ubO/zi0N+3uF4djPJtOTlpPdj8l4cNGN+FKByFmqWEixT+jYCuKObxwqkvnliSOvOdUenBYOBh1ph4fsv9jkg7XKdBCoKfIzUUVXzfOPmrtEf0kC4KrSnn5z7epxs20Gm8mNGDkZcxWEYPYxFaHzgs6Fi6p6+ol58hWIC0FpE/fRzcZu71kqqFEgOljR/0dxEG9Qjw3D7VITO/1W6d/3GvV1zXNmn/cNvjMpTnIeqgZiFwfUAVT9jFOzNvtEhW0zOH87kVuRvcPJu38GOvLUc+RLAsTqtyb4CBQOYdZApNeOy+9WLMbFE6dDpWWGZEasj/aU+5oKSsZ6JR3yPedG+smwA2Zw7AhhxcorPn1wR/VP/dUEINEViz8sFTbV0/5qFNq2r4ToHNXNMduAhbxDyuU/G/BHO2F2h5KpMJO0qRz+zkYjYQBaaIAiuL7AljWmkNN7/TNW7z+e00jcy+bRFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
